# =============================================================
# ALPHA BIST — Traefik Static Configuration
# =============================================================

api:
  dashboard: true
  insecure: true

entryPoints:
  web:
    address: ":80"
  websecure:
    address: ":443"

providers:
  docker:
    endpoint: "unix:///var/run/docker.sock"
    exposedByDefault: false
    network: bist-100-main_alpha-net
  file:
    directory: /etc/traefik/dynamic
    watch: true

ping:
  entryPoint: web

accessLog:
  bufferingSize: 100
